### PR TITLE
Added additonal notes as to how to deploy our flask server

### PR DESCRIPTION
**Pull request by WesMC**

### CODE REVIEW

**Comment by WesMC** [comment]
@flochner
@lozeki
@huongsterha

Please see my pull request

**Comment by huongsterha** [comment]
Looks good so far!

**Comment by flochner** [comment]
Looks good.  Nice markup.

**Comment by lozeki** [comment]
Thanks for remind me about my deployment.md. I just fixed it.
Your post is good and it has a nice layout.

**Pull request merged**
